<a href="https://colab.research.google.com/github/SabanaSultana/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors in Python**

# Creating a Tensor

In [71]:
import torch
print(torch.__version__)

2.9.0+cu128


In [72]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [73]:
# using empty
a = torch.empty(2,3)
a

tensor([[ 2.9768e-02,  4.4713e-41,  6.0453e+04],
        [-1.3232e-22,  3.1827e-02,  4.4713e-41]])

In [74]:
# check type
type(a)

torch.Tensor

In [75]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [76]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [77]:
# using rand
torch.rand(2,3)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [78]:
# manual_seed  ## Seed is used to generate same random numbers in each execution
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [79]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [80]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [81]:
# # using tensor
# torch.tensor([[1,2,4],[4,5]])  ## error

In [82]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))
print("using full ->", torch.full((3, 2), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
using full -> tensor([[5, 5],
        [5, 5],
        [5, 5]])


# Tensor Shapes

In [83]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [84]:
x.shape

torch.Size([2, 3])

In [85]:
torch.empty_like(x)  ## create an empty  tensor with dimension similar as x

tensor([[137044858558512,        11665392, 137044856463136],
        [137050524361200,        11664816, 137044856463184]])

In [86]:
torch.zeros_like(x)  ## create a zero tensor with dimension similar as x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [87]:
torch.rand_like(x, dtype=torch.float32)   ## As random function stores float value, you have to mention it here.

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [88]:
# find data type
x.dtype

torch.int64

In [89]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [90]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [91]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations in Tensor

## 1. Scalar Operation

In [92]:
x = torch.rand(2,2)
x

x.to(torch.int32)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [93]:
# addition
print(x + 2)
# substraction
print(x - 2)
# multiplication
print(x * 3)
# division
print(x / 3)
# int division
print((x * 100)//3)
# mod
print(((x * 100)//3)%2)
# power
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### 2. Element wise operation

In [94]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [95]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [96]:
c = torch.tensor([1, -2, 3, -4])

In [97]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [98]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [99]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [100]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [101]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [102]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [103]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [104]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [105]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [106]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [107]:
# median
torch.median(e)

tensor(0.)

In [108]:
# max and min
torch.max(e)
# torch.min(e)

tensor(9.)

In [109]:
# product
torch.prod(e)

tensor(0.)

In [110]:
# standard deviation
torch.std(e)
# variance
torch.var(e)
# argmax
torch.argmax(e)
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [111]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [112]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [113]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [114]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [115]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [116]:
# determinant
torch.det(h)

tensor(-110.)

In [117]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [118]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [119]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions ***

In [120]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [121]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [122]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [123]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [124]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [125]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [126]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [127]:
# Reduce memory usage

In [128]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [129]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [130]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [131]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [132]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [133]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [134]:
b = a   ## The concept of shallow copy and deep copy

In [135]:
b

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [136]:
a

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [137]:
a[0][0]=0

In [138]:
a

tensor([[0.0000, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [139]:
b

tensor([[0.0000, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [140]:
id(a)

137044828690608

In [141]:
id(b)

137044828690608

In [142]:
b=a.clone()

In [143]:
id(b)

137044828234336

In [144]:
id(a)

137044828690608

In [147]:
y=torch.tensor(([1,2,3],[5,6,7]))
y

tensor([[1, 2, 3],
        [5, 6, 7]])

In [148]:
z=y.clone()
z

tensor([[1, 2, 3],
        [5, 6, 7]])

In [149]:
id(y)

137044828775968

In [150]:
id(z)

137044828266864

###Tensor Operations On GPU

In [151]:
torch.cuda.is_available()

True

In [154]:
device=torch.device('cuda')

In [155]:
# Creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [156]:
f=torch.rand((2,3))
f


tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [157]:
g=f.to(device)

In [158]:
g

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]], device='cuda:0')

###Reshape

In [ ]:
# Reshape, Flatten, permute, unsqueez, squeez.  .... numpy to torch or torch to numpy conversion