<a href="https://colab.research.google.com/github/SabanaSultana/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors in Python**

# Creating a Tensor

In [1]:
import torch
print(torch.__version__)

2.9.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [4]:
# using empty
a = torch.empty(2,3)
a

tensor([[4.5447e+30, 3.0750e+29, 1.9284e+31],
        [1.8891e+31, 8.3195e+35, 2.1708e-18]])

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.0516, 0.3447, 0.9570],
        [0.1768, 0.9234, 0.3549]])

In [10]:
# manual_seed  ## Seed is used to generate same random numbers in each execution
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# # using tensor
# torch.tensor([[1,2,4],[4,5]])  ## error

In [17]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))
print("using full ->", torch.full((3, 2), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
using full -> tensor([[5, 5],
        [5, 5],
        [5, 5]])


# Tensor Shapes

In [18]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)  ## create an empty  tensor with dimension similar as x

tensor([[136872763252112,       194693680,       194831520],
        [      112919280,               0,       153896336]])

In [21]:
torch.zeros_like(x)  ## create a zero tensor with dimension similar as x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.rand_like(x, dtype=torch.float32)   ## As random function stores float value, you have to mention it here.

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])