<a href="https://colab.research.google.com/github/SabanaSultana/PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
if torch.cuda.is_available():
  print('GPU is present')
else:
  print("Gpu is not available")

GPU is present


# Creating a Tensor

In [ ]:
#using empty

a=torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
# using zeros and ones

torch.zeros(2,4)
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Random
torch.rand(2,3) ## every time this function gives different random values

tensor([[0.0314, 0.1080, 0.5424],
        [0.8851, 0.5296, 0.6896]])

In [ ]:
# seed + random    ## always same values ( in every execution ) given by random function
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor , custom tensor

torch.tensor([[1,2,3], [2,3,5], [1,2,6], [1,4,3]])

tensor([[1, 2, 3],
        [2, 3, 5],
        [1, 2, 6],
        [1, 4, 3]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [ ]:
# using linspace
print("using linspace ->", torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
# using eye
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# using full, 2nd parameter define every item's value

print("using full ->", torch.full((2,3), 5))
print("using full ->", torch.full((2,3), 6))

using full -> tensor([[5, 5, 5],
        [5, 5, 5]])
using full -> tensor([[6, 6, 6],
        [6, 6, 6]])


# Tensor Shapes


In [ ]:
x=torch.tensor([[1,2],[2,3], [3,4]])
x


tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
x.shape

torch.Size([3, 2])

In [ ]:
torch.empty_like(x)

tensor([[       10843584, 139064770408208],
        [139064770408288,        11653544],
        [139065215353552, 139065215358976]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [ ]:
# torch.rand_like(x)  ## As rand generates values in float between 0 to 1, so you will get error here as X contain Integers

## sol

torch.rand_like(x, dtype=torch.float)

tensor([[0.4183, 0.9014],
        [0.9969, 0.7565],
        [0.2239, 0.3023]])

In [ ]:
y=torch.tensor([1.2,3.4])

In [ ]:
y

tensor([1.2000, 3.4000])

In [ ]:
torch.rand_like(y)  ## here rand_like will work fine ad y has float values

tensor([0.2627, 0.0428])

In [ ]:
z=torch.tensor([[2.3,4.5], [5,6], [8.9, 9]])

In [ ]:
z

tensor([[2.3000, 4.5000],
        [5.0000, 6.0000],
        [8.9000, 9.0000]])

In [ ]:
torch.rand_like(z)

tensor([[0.2080, 0.1180],
        [0.1217, 0.7356],
        [0.7118, 0.7876]])

# Tensor DataTypes

In [ ]:
x.dtype, y.dtype, z.dtype

(torch.int64, torch.float32, torch.float32)

In [ ]:
torch.tensor([1.2,3.6], dtype=torch.int32)

tensor([1, 3], dtype=torch.int32)

In [ ]:
torch.tensor([3, 5], dtype=torch.float64)

tensor([3., 5.], dtype=torch.float64)

In [ ]:
# using to

x.to(torch.float64)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]], dtype=torch.float64)

# Tensor Mathematical Operations

## 1. With Scaler


In [ ]:
x = torch.rand(2,2)
x

tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0318, 0.6787],
        [0.3089, 0.9546]])

## 2. Tensor to Tensor ( Element wise operation)

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4450, 0.7278, 0.4563],
        [0.3389, 0.6211, 0.5530]])
tensor([[0.6896, 0.3687, 0.9053],
        [0.8356, 0.3039, 0.6726]])


In [ ]:
# add
print(a + b)
# sub
print(a - b)
# multiply
print(a * b)
# division
print(a / b)
# power
print(a ** b)
# mod
print(a % b)

tensor([[1.1346, 1.0966, 1.3615],
        [1.1744, 0.9251, 1.2256]])
tensor([[-0.2446,  0.3591, -0.4490],
        [-0.4967,  0.3172, -0.1196]])
tensor([[0.3069, 0.2684, 0.4130],
        [0.2831, 0.1888, 0.3720]])
tensor([[0.6453, 1.9738, 0.5040],
        [0.4055, 2.0439, 0.8222]])
tensor([[0.5722, 0.8895, 0.4915],
        [0.4049, 0.8653, 0.6714]])
tensor([[0.4450, 0.3591, 0.4563],
        [0.3389, 0.0133, 0.5530]])


In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 4., 3.],
        [8., 8., 3.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([ 7., 19.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 6., 3.])

In [ ]:
# median
torch.median(e)

tensor(3.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [ ]:
# variance
torch.var(e)

tensor(9.8667)

In [ ]:
# argmax, max value's position
torch.argmax(e)

tensor(3)

In [ ]:
# argmin, min value's position
torch.argmin(e)

tensor(0)

## 4. Matrix Operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 5, 0],
        [6, 4, 0]])
tensor([[8, 4],
        [7, 2],
        [3, 8]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[59, 22],
        [76, 32]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [5, 4],
        [0, 0]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 6., 2.],
        [9., 5., 0.],
        [4., 2., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(-207.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.1691,  0.1836,  0.0483],
        [ 0.3043, -0.1304, -0.0870],
        [ 0.0097, -0.0676,  0.1401]])

## 5. Comparison Operator

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 1, 5],
        [4, 4, 1]])
tensor([[1, 2, 4],
        [7, 2, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[False,  True,  True],
        [ True,  True,  True]])

## 6. Special Functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 3., 1.],
        [0., 2., 1.]])

In [ ]:
# log
torch.log(k)

tensor([[0.6931, 1.0986, 0.0000],
        [  -inf, 0.6931, 0.0000]])

In [ ]:
# exp
torch.exp(k)

tensor([[ 7.3891, 20.0855,  2.7183],
        [ 1.0000,  7.3891,  2.7183]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 1.7321, 1.0000],
        [0.0000, 1.4142, 1.0000]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9526, 0.7311],
        [0.5000, 0.8808, 0.7311]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.7311, 0.5000],
        [0.1192, 0.2689, 0.5000]])

In [ ]:
# relu
torch.relu(k)

tensor([[2., 3., 1.],
        [0., 2., 1.]])

# Inplace Operations

In [7]:
m = torch.randint(low=0, high=10, size=(2,3), dtype=torch.int32)
n = torch.randint(low=0, high=10, size=(2,3), dtype=torch.int32)

print(m)
print(n)

tensor([[0, 7, 9],
        [0, 3, 4]], dtype=torch.int32)
tensor([[5, 0, 9],
        [1, 0, 2]], dtype=torch.int32)


In [8]:
m+n

tensor([[ 5,  7, 18],
        [ 1,  3,  6]], dtype=torch.int32)

In [9]:
m.add_(n)
m

tensor([[ 5,  7, 18],
        [ 1,  3,  6]], dtype=torch.int32)

In [10]:
n

tensor([[5, 0, 9],
        [1, 0, 2]], dtype=torch.int32)

In [11]:
torch.relu(m)

tensor([[ 5,  7, 18],
        [ 1,  3,  6]], dtype=torch.int32)

In [12]:
m.relu_()

tensor([[ 5,  7, 18],
        [ 1,  3,  6]], dtype=torch.int32)

In [13]:
m

tensor([[ 5,  7, 18],
        [ 1,  3,  6]], dtype=torch.int32)

# Copying a Tensor

In [14]:
a=torch.randint(low=0, high=10, size=(2,3), dtype=torch.int32)
a

tensor([[5, 4, 5],
        [5, 2, 3]], dtype=torch.int32)

In [15]:
## Shallow Copy
b=a

In [16]:
b

tensor([[5, 4, 5],
        [5, 2, 3]], dtype=torch.int32)

In [17]:
id(a)

135363347077216

In [18]:
id(b)

135363347077216

In [19]:
a[0][0]=100

In [20]:
a

tensor([[100,   4,   5],
        [  5,   2,   3]], dtype=torch.int32)

In [21]:
b

tensor([[100,   4,   5],
        [  5,   2,   3]], dtype=torch.int32)

In [23]:
## Deep copy
c=torch.clone(a)

In [24]:
c

tensor([[100,   4,   5],
        [  5,   2,   3]], dtype=torch.int32)

In [25]:
a[0][0]=500

In [26]:
a

tensor([[500,   4,   5],
        [  5,   2,   3]], dtype=torch.int32)

In [27]:
c

tensor([[100,   4,   5],
        [  5,   2,   3]], dtype=torch.int32)

In [28]:
id(a)

135363347077216

In [29]:
id(c)

135363016714880

# Creation & Execution of Tensor on GPU

In [31]:
torch.cuda.is_available()

True

In [38]:
device=torch.device('cuda')
device

device(type='cuda')

In [41]:
## Creating a tensor on GPU
a=torch.rand((2,3), device=device)
# a=torch.rand(2,3, device=device)

In [42]:
a

tensor([[0.9737, 0.2160, 0.5077],
        [0.4687, 0.7207, 0.7826]], device='cuda:0')

In [44]:
## Moving existing tensor on gpu
b=torch.rand(2,3)
b

tensor([[0.7810, 0.8222, 0.2665],
        [0.3464, 0.6866, 0.2380]])

In [45]:
b=b.to(device)

In [46]:
b

tensor([[0.7810, 0.8222, 0.2665],
        [0.3464, 0.6866, 0.2380]], device='cuda:0')

In [47]:
b+5

tensor([[5.7810, 5.8222, 5.2665],
        [5.3464, 5.6866, 5.2380]], device='cuda:0')

Time Measurement between CPU and GPU

In [48]:
import time

In [49]:
time.time()

1775539970.209427

In [61]:
size=1000

# torch.manual_seed(10)  ##// here 10 is seed value which define starting point, it could be any value
mat_1=torch.rand(size,size)
mat_2=torch.rand(size,size)

print(mat_1)
print(mat_2)

## Measure time on CPU
start_time=time.time()

mat_mul=torch.matmul(mat_1, mat_2)

cpu_time=time.time() - start_time

print(f"Matrix Multiplication time on CPU {cpu_time: .4f} seconds")

## Moving to GPU

mat_1=mat_1.to(device)
mat_2=mat_2.to(device)

## Measure time on GPU

## Measure time on CPU
start_time=time.time()

mat_mul=torch.matmul(mat_1, mat_2)
torch.cuda.synchronize() # ensure all GPU operations are completed

GPU_time= time.time() - start_time

print(f"Matrix Multiplication time on GPU {GPU_time: .4f} seconds")


tensor([[0.2428, 0.9603, 0.1005,  ..., 0.3072, 0.3340, 0.5476],
        [0.3798, 0.1134, 0.7026,  ..., 0.5069, 0.4162, 0.9214],
        [0.2296, 0.6886, 0.0229,  ..., 0.6830, 0.2235, 0.7044],
        ...,
        [0.5687, 0.6915, 0.9531,  ..., 0.6296, 0.4172, 0.2557],
        [0.1001, 0.3266, 0.8173,  ..., 0.8600, 0.8896, 0.8371],
        [0.7053, 0.0455, 0.6198,  ..., 0.2743, 0.8561, 0.8996]])
tensor([[0.7016, 0.1632, 0.6677,  ..., 0.7812, 0.2477, 0.0807],
        [0.7157, 0.8424, 0.8167,  ..., 0.5267, 0.3861, 0.4406],
        [0.8233, 0.2826, 0.4741,  ..., 0.0691, 0.1104, 0.0530],
        ...,
        [0.0725, 0.4597, 0.9880,  ..., 0.4919, 0.5917, 0.6034],
        [0.5000, 0.4474, 0.0737,  ..., 0.3175, 0.3997, 0.7480],
        [0.6458, 0.1408, 0.9006,  ..., 0.3938, 0.0965, 0.0556]])
Matrix Multiplication time on CPU  0.0174 seconds
Matrix Multiplication time on GPU  0.0010 seconds


# Reshape Tensor

In [62]:
a=torch.ones(4,4)

In [63]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [64]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [67]:
# a.reshape(2,2,2) error , all values must come

In [69]:
#flatten
a.flatten()  # converting to one dimension


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
b=torch.rand(2,3,4)

In [71]:
b

tensor([[[0.8700, 0.5131, 0.7182, 0.6106],
         [0.2798, 0.7840, 0.1673, 0.9470],
         [0.3689, 0.2036, 0.6518, 0.4530]],

        [[0.3447, 0.5325, 0.9582, 0.2569],
         [0.6921, 0.8255, 0.5635, 0.3514],
         [0.9013, 0.0676, 0.4845, 0.7327]]])

In [73]:
b.shape

torch.Size([2, 3, 4])

In [76]:
#permute
c=b.permute(2,1,0)

In [78]:
c

tensor([[[0.8700, 0.3447],
         [0.2798, 0.6921],
         [0.3689, 0.9013]],

        [[0.5131, 0.5325],
         [0.7840, 0.8255],
         [0.2036, 0.0676]],

        [[0.7182, 0.9582],
         [0.1673, 0.5635],
         [0.6518, 0.4845]],

        [[0.6106, 0.2569],
         [0.9470, 0.3514],
         [0.4530, 0.7327]]])

In [77]:
c.shape

torch.Size([4, 3, 2])

In [79]:
b

tensor([[[0.8700, 0.5131, 0.7182, 0.6106],
         [0.2798, 0.7840, 0.1673, 0.9470],
         [0.3689, 0.2036, 0.6518, 0.4530]],

        [[0.3447, 0.5325, 0.9582, 0.2569],
         [0.6921, 0.8255, 0.5635, 0.3514],
         [0.9013, 0.0676, 0.4845, 0.7327]]])

In [80]:
d=b.permute(2,0,1)

In [81]:
d.shape

torch.Size([4, 2, 3])

In [82]:
d

tensor([[[0.8700, 0.2798, 0.3689],
         [0.3447, 0.6921, 0.9013]],

        [[0.5131, 0.7840, 0.2036],
         [0.5325, 0.8255, 0.0676]],

        [[0.7182, 0.1673, 0.6518],
         [0.9582, 0.5635, 0.4845]],

        [[0.6106, 0.9470, 0.4530],
         [0.2569, 0.3514, 0.7327]]])

In [83]:
#unsqueez
#image size

x=torch.rand(256,256,3)

In [84]:
x

tensor([[[0.0985, 0.6677, 0.2313],
         [0.7109, 0.9966, 0.1153],
         [0.4120, 0.8853, 0.4366],
         ...,
         [0.2804, 0.1017, 0.2086],
         [0.1010, 0.6743, 0.4724],
         [0.6684, 0.3243, 0.5662]],

        [[0.5873, 0.9671, 0.9137],
         [0.1539, 0.3895, 0.8669],
         [0.7597, 0.7475, 0.0920],
         ...,
         [0.8961, 0.9449, 0.0269],
         [0.7525, 0.6255, 0.8409],
         [0.8261, 0.9485, 0.3620]],

        [[0.1510, 0.4934, 0.4290],
         [0.4510, 0.3132, 0.7853],
         [0.4725, 0.4982, 0.5046],
         ...,
         [0.2512, 0.7062, 0.5032],
         [0.0338, 0.2469, 0.0139],
         [0.7470, 0.3263, 0.4855]],

        ...,

        [[0.7984, 0.2868, 0.0552],
         [0.4888, 0.3202, 0.2982],
         [0.3396, 0.3429, 0.6143],
         ...,
         [0.2500, 0.9542, 0.6721],
         [0.7887, 0.6921, 0.2357],
         [0.8684, 0.6371, 0.7735]],

        [[0.1580, 0.3302, 0.1282],
         [0.9812, 0.0751, 0.4865],
         [0.

In [85]:
x.unsqueeze(0).shape ## Adding a new dimension to a position

torch.Size([1, 256, 256, 3])

In [86]:
x.unsqueeze(1).shape

torch.Size([256, 1, 256, 3])

In [96]:
#squeez

y=torch.rand(1,20,2)
y

tensor([[[0.4508, 0.5924],
         [0.9827, 0.0792],
         [0.7831, 0.2586],
         [0.9759, 0.2583],
         [0.6997, 0.9315],
         [0.6601, 0.7217],
         [0.4479, 0.6641],
         [0.3266, 0.1851],
         [0.3084, 0.4732],
         [0.8783, 0.7054],
         [0.7737, 0.7802],
         [0.8433, 0.2489],
         [0.5709, 0.0627],
         [0.0239, 0.2123],
         [0.2331, 0.3916],
         [0.3179, 0.5368],
         [0.0871, 0.2035],
         [0.4264, 0.7043],
         [0.1882, 0.1405],
         [0.2218, 0.8912]]])

In [97]:
y.shape

torch.Size([1, 20, 2])

In [105]:
z=y.squeeze(0)

In [107]:
z.shape

torch.Size([20, 2])

In [108]:
z

tensor([[0.4508, 0.5924],
        [0.9827, 0.0792],
        [0.7831, 0.2586],
        [0.9759, 0.2583],
        [0.6997, 0.9315],
        [0.6601, 0.7217],
        [0.4479, 0.6641],
        [0.3266, 0.1851],
        [0.3084, 0.4732],
        [0.8783, 0.7054],
        [0.7737, 0.7802],
        [0.8433, 0.2489],
        [0.5709, 0.0627],
        [0.0239, 0.2123],
        [0.2331, 0.3916],
        [0.3179, 0.5368],
        [0.0871, 0.2035],
        [0.4264, 0.7043],
        [0.1882, 0.1405],
        [0.2218, 0.8912]])

In [92]:
# y.shape

torch.Size([1, 20])

# Example & Understanding of Multi Dimension Tensor

In [110]:
## 1D
a=torch.rand(2)
a

tensor([0.0859, 0.7365])

In [112]:
## 2D
b=torch.rand(2,3)
b

tensor([[0.8662, 0.3771, 0.4523],
        [0.2240, 0.8864, 0.0285]])

In [119]:
o=b.unsqueeze(1)
print(o.shape)
print(o)

torch.Size([2, 1, 3])
tensor([[[0.8662, 0.3771, 0.4523]],

        [[0.2240, 0.8864, 0.0285]]])


In [123]:
b=torch.rand(1,2,3)  ## squeeze can only be happen if the last dimension (0th) is 1 ******
print(b)
p=b.squeeze(0)
print(p.shape)
print(p)

tensor([[[0.8556, 0.1344, 0.5292],
         [0.0912, 0.2145, 0.5958]]])
torch.Size([2, 3])
tensor([[0.8556, 0.1344, 0.5292],
        [0.0912, 0.2145, 0.5958]])


In [113]:
## 3D
c=torch.rand(2,3,2)
c

tensor([[[0.1948, 0.3528],
         [0.4832, 0.3544],
         [0.6705, 0.0181]],

        [[0.5464, 0.7072],
         [0.9540, 0.8718],
         [0.7030, 0.1969]]])

In [114]:
## 4D
d=torch.rand(2,3,4,2)
d

tensor([[[[0.7612, 0.2467],
          [0.6786, 0.9325],
          [0.7871, 0.8031],
          [0.9656, 0.4248]],

         [[0.4249, 0.9546],
          [0.3348, 0.0438],
          [0.6737, 0.5010],
          [0.2688, 0.3332]],

         [[0.5101, 0.7097],
          [0.3173, 0.3436],
          [0.6705, 0.1594],
          [0.2454, 0.2688]]],


        [[[0.3301, 0.3877],
          [0.7695, 0.4932],
          [0.6404, 0.7630],
          [0.8333, 0.2510]],

         [[0.9282, 0.4439],
          [0.4691, 0.5600],
          [0.3187, 0.6729],
          [0.4837, 0.8621]],

         [[0.6225, 0.9693],
          [0.2196, 0.6553],
          [0.0974, 0.9318],
          [0.4173, 0.5565]]]])

# NumPy & PyTorch

In [124]:
import numpy as np


In [132]:
# a=torch.rand(3)
a=torch.rand(2,3)
a

tensor([[0.9151, 0.3982, 0.1882],
        [0.3275, 0.5191, 0.3697]])

In [133]:
type(a)

torch.Tensor

In [134]:
b=a.numpy()
b

array([[0.91511554, 0.3981989 , 0.18821537],
       [0.32751036, 0.51906174, 0.3697043 ]], dtype=float32)

In [135]:
type(b)

numpy.ndarray

In [137]:
x=np.array([[2,3], [3,4]])

In [138]:
x

array([[2, 3],
       [3, 4]])

In [141]:
y=torch.from_numpy(x)
y

tensor([[2, 3],
        [3, 4]])

In [142]:
y.shape

torch.Size([2, 2])

In [143]:
type(y)

torch.Tensor